// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneAPI.Models;

namespace PhoneAPI.Migrations
{
    [DbContext(typeof(PhoneDetailContext))]
    [Migration("20191217160951_InitialPhoneTable")]
    partial class InitialPhoneTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhoneAPI.Models.PhoneDetail", b =>
                {
                    b.Property<string>("PhoneSid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeExpired")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("PhoneSid");

                    b.ToTable("PhoneDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
